### ISSUE TITLE
howto "Watch an unknown tool"  

### ISSUE THREAD

**Issue by nbari** [nko4/bazinga#1]
I would like to use your project to monitor the status of some a gearman servers

the command I use to produce stats/data is:

```
 watch -t -n 1 gearadmin --status
```

From http://gearman.org/protocol/

status
   This sends back a list of all registered functions.  Next to
    each function is the number of jobs in the queue, the number of
    running jobs, and the number of capable workers. The columns are
    tab separated, and the list is terminated with a line containing
    a single '.' (period). The format is:

```
FUNCTION\tTOTAL\tRUNNING\tAVAILABLE_WORKERS
```

example of data to be plotted:

<pre>
images    0    0   16
audio     10   0    0
video     0    0   16
.
</pre>

Is tried to create a gearman.json and to specify fields with something like:

```
"function": {
    "type": "line"
    "fields": [0] <---- column
    ...
```

Based on this data, could you guys give an example of how to properly create custom config files that could help parse/plot any kind of data.

thanks in advance.

**Comment by eendeego** [comment]
Hi, @nbari, I took a look at gearman's documentation.

We have to solve two issues before being capable of solving this:
1.  We need to support multi-line samples - which we should already be doing because sar, for instance, sends a line for each CPU core.
2.  We need to support watch-like functionality - as nodestatus is working now, it expects the tools that it executes to keep running endlessly.
